version: "3.3"

services:
  database:
    container_name: analytics_database
    image: postgres
    restart: always
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      - COMPOSE_PROJECT_NAME=plataforma
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=plataforma
      - POSTGRES_USER=plataforma
    ports:
      - 5432:5432
  
#  redis:
#    image: redis
#    ports:
#      - 6379:6379
#
