import pytz
from decouple import config

PYTHONPRO_DATABASE_URL = config("PYTHONPRO_DATABASE_URL")

ANALYTICS_DATABASE_URL = config("ANALYTICS_DATABASE_URL")

SPREADSHEET_KEY = config("SPREADSHEET_KEY")

PAGARME_API_KEY = config("PAGARME_API_KEY")

TIME_ZONE = pytz.timezone("America/Sao_Paulo")

TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN")

ACTIVE_CAMPAIGN_URL = config("ACTIVE_CAMPAIGN_URL")

ACTIVE_CAMPAIGN_KEY = config("ACTIVE_CAMPAIGN_KEY")